# ---- Stage 1: Build ----
FROM maven:3.9.15-eclipse-temurin-25-alpine AS builder

WORKDIR /app

# Copy only what's needed first (better caching)
COPY pom.xml .

# Now copy source
COPY src ./src

# Build the jar
RUN mvn clean package

# ---- Stage 2: Runtime ----
FROM eclipse-temurin:25.0.3_9-jre-alpine-3.23

WORKDIR /app

# Copy the built artifact from builder
COPY --from=builder /app/target/*.jar app.jar

EXPOSE 8080
ENTRYPOINT ["java", "-jar", "app.jar"]